[package]
name = "bitcoind"
version = "0.15.0"
authors = ["Riccardo Casatta <riccardo@casatta.it>"]
description = "Utility to run a regtest bitcoind process, useful in integration testing environment"
license = "MIT"
repository = "https://github.com/RCasatta/bitcoind"
documentation = "https://docs.rs/bitcoind/"
edition = "2018"

[dependencies]
core-rpc = "0.14"
tempfile = "3.1"
log = "0.4"
home = "0.5.3"  # use same ver in build-dep

[dev-dependencies]
env_logger = "0.8"

[build-dependencies]
ureq = "2.1"
bitcoin_hashes = "0.9"
flate2 = "1.0"
tar = "0.4"
home = "0.5.3"

[features]
"0_21_1" = []
"0_21_0" = []
"0_20_1" = []
"0_20_0" = []
"0_19_1" = []
"0_19_0_1" = []
"0_18_1" = []
"0_18_0" = []
"0_17_1" = []
